2017-03-26 10:22:13,911 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 10:22:43,268 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 10:22:58,494 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 10:26:52,676 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 10:27:05,401 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 10:27:41,663 ERROR: Exception on /callback/twitter [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 71, in oauth_callback
    nickname = User.make_unique_nickname(nickname)
UnboundLocalError: local variable 'nickname' referenced before assignment
2017-03-26 10:29:42,621 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 10:29:49,914 ERROR: Exception on /callback/twitter [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 71, in oauth_callback
    user.nickname = User.make_unique_nickname(nickname)
NameError: global name 'nickname' is not defined
2017-03-26 10:31:06,719 ERROR: Exception on /callback/twitter [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 71, in oauth_callback
    # user.nickname = User.make_unique_nickname(nickname)
NameError: global name 'nickname' is not defined
2017-03-26 10:32:22,434 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 10:32:45,041 ERROR: Exception on /callback/twitter [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 70, in oauth_callback
    user = User(social_id=social_id, nickname=make_unique_nickname(username), email=email)
NameError: global name 'make_unique_nickname' is not defined
2017-03-26 10:33:18,101 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:23:05,610 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:23:37,332 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:25:33,894 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:25:40,173 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index2'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:27:28,298 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:27:40,171 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index2'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:30:00,749 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:30:08,290 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index2'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:34:10,049 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:34:18,683 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index2'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:36:27,690 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:39:23,734 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:39:34,472 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index2'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:40:10,182 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index2'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:40:20,438 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:40:27,151 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index2'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:41:07,991 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-03-26 11:42:42,997 ERROR: Exception on /callback/google [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/app/views.py", line 75, in oauth_callback
    return redirect(url_for('index'))
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index2'. Did you mean 'index' instead?
2017-03-26 11:42:58,693 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 12:54:00,580 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 12:55:05,814 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 13:00:41,014 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 13:02:05,510 ERROR: Exception on /user/dicriseg [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ed/microblog/app/views.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ed/microblog/app/templates/base.html", line 27, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ed/microblog/app/templates/user.html", line 7, in block "content"
    <td><img src="{{user.avatar(128)}}"></td>
  File "/home/ed/microblog/app/models.py", line 33, in avatar
    return 'http://www.gravatar.com/avatar/%s?d=mm&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)
AttributeError: 'NoneType' object has no attribute 'encode'
2017-04-22 13:02:39,256 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 13:02:43,604 ERROR: Exception on /user/dicriseg [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ed/microblog/app/views.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ed/microblog/app/templates/base.html", line 27, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ed/microblog/app/templates/user.html", line 7, in block "content"
    <td><img src="{{user.avatar(128)}}"></td>
  File "/home/ed/microblog/app/models.py", line 33, in avatar
    return 'http://www.gravatar.com/avatar/%s?d=mm&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)
AttributeError: 'NoneType' object has no attribute 'encode'
2017-04-22 13:03:19,634 ERROR: Exception on /user/dicriseg [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ed/microblog/app/views.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ed/microblog/app/templates/base.html", line 27, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ed/microblog/app/templates/user.html", line 7, in block "content"
    <td><img src="{{user.avatar(128)}}"></td>
  File "/home/ed/microblog/app/models.py", line 33, in avatar
    return 'http://www.gravatar.com/avatar/%s?d=mm&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)
AttributeError: 'NoneType' object has no attribute 'encode'
2017-04-22 13:03:20,950 ERROR: Exception on /user/dicriseg [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ed/microblog/app/views.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ed/microblog/app/templates/base.html", line 27, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ed/microblog/app/templates/user.html", line 7, in block "content"
    <td><img src="{{user.avatar(128)}}"></td>
  File "/home/ed/microblog/app/models.py", line 33, in avatar
    return 'http://www.gravatar.com/avatar/%s?d=mm&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)
AttributeError: 'NoneType' object has no attribute 'encode'
2017-04-22 13:03:21,550 ERROR: Exception on /user/dicriseg [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ed/microblog/app/views.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ed/microblog/app/templates/base.html", line 27, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ed/microblog/app/templates/user.html", line 7, in block "content"
    <td><img src="{{user.avatar(128)}}"></td>
  File "/home/ed/microblog/app/models.py", line 33, in avatar
    return 'http://www.gravatar.com/avatar/%s?d=mm&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)
AttributeError: 'NoneType' object has no attribute 'encode'
2017-04-22 13:03:30,663 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 13:03:34,093 ERROR: Exception on /user/dicriseg [GET] [in /home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/ed/microblog/app/views.py", line 95, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ed/microblog/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ed/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ed/microblog/app/templates/base.html", line 27, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ed/microblog/app/templates/user.html", line 7, in block "content"
    <td><img src="{{user.avatar(128)}}"></td>
  File "/home/ed/microblog/app/models.py", line 33, in avatar
    return 'http://www.gravatar.com/avatar/%s?d=mm&s=%d' % (md5(self.email.encode('utf-8')).hexdigest(), size)
AttributeError: 'NoneType' object has no attribute 'encode'
2017-04-22 13:03:50,524 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 13:03:50,745 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 13:07:00,662 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-22 13:07:00,850 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:02:21,465 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:02:21,600 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:07:42,283 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:07:42,418 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:11:38,345 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:18:15,593 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:18:47,494 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:18:47,651 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:19:10,242 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:19:16,242 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-23 12:19:16,378 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-24 08:40:04,683 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-24 08:40:24,459 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-24 08:40:24,607 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-24 08:54:27,098 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-24 09:07:57,140 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-24 09:08:18,464 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-29 13:05:57,904 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-29 13:10:15,110 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-29 13:11:15,031 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-29 13:18:57,937 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-04-29 13:18:58,087 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 14:57:35,152 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 14:57:51,878 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 14:57:52,068 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 14:58:34,412 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 15:00:24,921 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 15:02:01,393 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 15:02:15,600 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 15:02:47,736 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 15:02:57,527 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-03 15:02:57,659 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-04 15:48:23,336 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-04 15:48:23,483 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-04 15:49:46,905 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-04 15:56:08,272 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-04 15:56:48,556 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-04 15:57:02,758 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:09:11,671 INFO: microblog startup [in app/__init__.py:33]
2017-05-05 17:10:19,633 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:10:19,819 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:11:20,354 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:12:28,891 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:12:35,775 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:12:45,072 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:12:45,287 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:14:12,899 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:15:41,519 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-05 17:16:00,833 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:33]
2017-05-06 05:50:02,623 INFO: microblog startup [in app/__init__.py:34]
2017-05-06 05:53:13,607 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:34]
2017-05-06 05:53:13,803 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:34]
2017-05-06 05:53:33,378 INFO: microblog startup [in app/__init__.py:34]
2017-05-06 05:54:48,124 INFO: microblog startup [in app/__init__.py:36]
2017-05-06 06:02:36,512 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:02:36,701 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:05:19,551 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:06:57,135 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:09:07,532 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:09:07,708 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:17:47,990 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:17:48,167 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:29:44,678 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:29:44,856 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:31:10,820 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:31:10,994 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:41:00,210 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 06:41:00,385 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 07:16:00,774 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 07:16:00,950 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:36]
2017-05-06 13:22:54,700 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:38]
2017-05-06 13:22:54,902 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:38]
2017-05-06 13:24:07,736 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:38]
2017-05-06 13:24:07,911 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:38]
2017-05-06 15:32:25,615 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:38]
2017-05-06 15:33:31,078 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:38]
2017-05-06 15:34:17,472 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:38]
2017-05-07 06:28:14,230 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 06:28:37,034 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 06:28:37,227 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 06:30:35,900 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 06:31:55,420 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 06:36:04,608 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 06:36:40,956 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 07:54:09,976 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 07:54:10,158 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 07:55:44,059 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 07:55:44,234 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:23:26,465 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:23:26,657 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:27:59,453 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:27:59,647 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:28:30,979 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:29:36,978 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:29:37,158 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:30:58,573 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:30:58,752 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:31:47,144 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:34:34,613 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:34:34,791 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:37:36,710 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:37:40,932 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:38:03,382 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:38:03,566 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:39:54,192 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:41:57,759 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:41:57,938 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:43:46,579 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:45:27,295 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:45:27,474 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:46:20,913 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:46:21,087 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:47:00,438 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:47:53,870 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:48:22,180 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:48:31,420 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:42]
2017-05-07 09:51:46,391 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:44]
2017-05-07 09:53:48,754 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-07 09:53:48,932 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-07 10:11:15,380 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-07 10:11:15,573 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-07 10:11:37,864 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-07 10:11:47,093 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-07 10:12:56,108 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-07 10:12:56,281 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-16 16:41:26,946 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-16 16:42:02,652 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-16 16:46:01,283 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-16 16:46:01,900 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-16 17:04:18,863 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-16 17:23:29,707 INFO: microblog startup [in app/__init__.py:59]
2017-05-16 17:24:59,008 INFO: microblog startup [in app/__init__.py:59]
2017-05-16 17:25:45,677 INFO: microblog startup [in app/__init__.py:59]
2017-05-16 17:26:19,524 INFO: microblog startup [in app/__init__.py:59]
2017-05-16 17:28:53,789 INFO: microblog startup [in app/__init__.py:59]
2017-05-16 17:33:46,368 INFO: microblog startup [in app/__init__.py:59]
2017-05-16 17:37:57,936 INFO: microblog startup [in app/__init__.py:59]
2017-05-16 17:40:43,442 INFO: microblog startup [in app/__init__.py:59]
2017-05-20 07:00:36,073 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:00:36,808 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:14:25,788 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:15:32,638 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:16:02,157 INFO: microblog startup [in app/__init__.py:59]
2017-05-20 07:16:58,855 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:18:36,120 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:18:49,328 INFO: microblog startup [in app/__init__.py:59]
2017-05-20 07:35:51,236 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:36:14,089 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:36:34,277 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:37:13,448 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:37:37,222 INFO: microblog startup [in app/__init__.py:59]
2017-05-20 07:40:05,168 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:40:48,723 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:40:49,255 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:42:04,111 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:42:31,583 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:42:32,108 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:43:57,857 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:43:58,383 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:44:28,753 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:44:29,289 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:45:07,045 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:45:07,574 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:47:23,992 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:47:24,524 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:48:25,350 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:48:28,951 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:48:31,516 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:49:27,287 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:51:31,329 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:52:08,048 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:52:56,823 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:54:23,247 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:54:23,777 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:56:52,704 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 07:56:53,259 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 09:02:47,651 INFO: microblog startup [in app/__init__.py:59]
2017-05-20 11:26:12,001 INFO: microblog startup [in app/__init__.py:59]
2017-05-20 11:32:00,174 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 11:32:00,711 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 11:32:53,472 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 11:33:12,106 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 11:34:46,046 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
2017-05-20 11:35:19,826 INFO: microblog startup [in /home/ed/microblog/app/__init__.py:59]
